// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderSchemaAPI.Models
{
    public partial class Order
    {
        public Order()
        {
            DeliveryAddress = new HashSet<DeliveryAddress>();
            Items = new HashSet<Item>();
            PickupAddress = new HashSet<PickupAddress>();
        }

        public int OrderId { get; set; }
        public DateTime RequestedPickupTime { get; set; }
        public virtual ICollection<DeliveryAddress> DeliveryAddress { get; set; }
        public virtual ICollection<PickupAddress> PickupAddress { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public string PickupInstructions { get; set; }
        public string DeliveryInstructions { get; set; }
    }
}