// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderSchemaAPI.Models
{
    public partial class PickupAddress
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int Unit { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public int Postcode { get; set; }

        public virtual Order Order { get; set; }
    }
}